swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user:
    x-swagger-router-controller: userController
    post:
      description: Create user data
      # used as the method name of the controller
      operationId: postUser
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Data to create the user.
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "201":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/{userCode}:
    x-swagger-router-controller: userController
    get:
      description: Get user data
      operationId: getUser
      parameters:
        - in: path
          name: userCode
          description: The user code.
          required: true
          type: string
        - in: query
          name: v
          description: The version of the exam
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /exam/{year}:
    x-swagger-router-controller: examController
    get:
      description: Create exam data
      operationId: getExamByYear
      parameters:
        - in: path
          name: year
          description: The year of the exam
          required: true
          type: integer
        - in: query
          name: v
          description: The version of the exam
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create exam data
      operationId: postExam
      consumes:
        - application/json
      parameters:
        - in: path
          name: year
          description: The year of the exam
          required: true
          type: integer
        - in: query
          name: v
          description: The version of the exam
          required: false
          type: integer
        - in: body
          name: questions
          description: Data with the questions of the exam
          required: true
          schema:
            items:
              type: object
              required:
                - id
                - statement
              properties:
                id:
                  type: string
                impugned:
                  type: boolean
                statement:
                  type: string
                answers:
                  type: array
                correctAnswer:
                  type: integer
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserResponse:
    required:
      - message
      - data
    properties:
      message:
        type: string
      data:
        type: object
